<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CdxSwapper</AssemblyName>
    <Version>1.0.2</Version>
    <ApplicationIcon>..\icon.ico</ApplicationIcon>
    <RootNamespace>CdxSwapper</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.20" />
    <EmbeddedResource Include="Sessions/Web/**/*" />
    <EmbeddedResource Include="Sessions/session_import.md" />
  </ItemGroup>
</Project>
