<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CdxSwapper</AssemblyName>
    <ApplicationIcon>..\icon.ico</ApplicationIcon>
    <RootNamespace>CdxSwapper</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
